config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  resources :payment_form, only: [:index]
  resources :products, except: [:edit, :update]
  resources :orders, only: [:index] do
    collection do
      get :new_complete
      get :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product

  enum status: { pending: 'pending', complete: 'complete' }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, presence: true

  after_create :create_in_stripe

  def create_in_stripe
    stripe_product = Stripe::Product.create({name: name})
    stripe_price = Stripe::Price.create({
                                   currency: 'usd',
                                   unit_amount: price_in_cents,
                                   product: stripe_product.id,
                                 })

    update(stripe_product_id: stripe_product.id, stripe_price_id: stripe_price.id)
  end

  def price_in_cents
    (price * 100).to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_VALIDATION_MESSAGE = 'must have at least 10 characters and at most 16 characters, contain at least one lowercase character, one uppercase character and one digit, and cannot contain three repeating characters in a row'

  validates :name, presence: true
  validates :password, presence: true,
            length: { in: 10..16 },
            format: {
              with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?!.*(.)\1{2,}).*\z/,
              message: PASSWORD_VALIDATION_MESSAGE
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError do |exception|
    respond_to do |format|
      format.html { redirect_to root_path, flash: { notice: exception.message } }
      format.turbo_stream do
        flash.now[:notice] = exception.message
        render_flash
      end
    end
  end

  def render_flash
    render turbo_stream: turbo_stream.update('flash_messages', partial: 'application/flash')
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_product, only: [:new_complete]
  before_action :set_order, only: [:complete]

  def index
    @orders = Order.all
  end

  def new_complete
    @payment_intent = Stripe::PaymentIntent.create(
      amount: @product.price_in_cents,
      currency: 'usd'
    )

    @order = Order.create(product: @product, stripe_payment_intent_id: @payment_intent.id)
  end

  def complete
    @order.complete!
    redirect_to orders_path, flash: { success: 'Order successfully completed.' }
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/payment_form_controller.rb
class PaymentFormController < ApplicationController
  def index
    @payment_intent = Stripe::PaymentIntent.create(
      amount: 1000,
      currency: 'usd'
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:destroy]

  def index
    set_products
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(permitted_params)

    if @product.save
      redirect_to products_path, flash: { success: 'Product successfully created' }
    else
      flash.now[:errors] = @product.errors.full_messages
      render_flash
    end
  end

  def destroy
    raise(StandardError, 'There are orders attached to this product and it cannot be deleted') if Order.where(product_id: @product.id).exists?
    @product.destroy
    redirect_to products_path, flash: { success: 'Product successfully deleted.' }
  end

  private

  def set_products
    @products = Product.all
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def permitted_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |_message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light ps-4 mb-4">
  <div class="container-fluid">
    <%= link_to 'Yeeld Exercise', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Orders', orders_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yeeld Exercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>

    <%= yield(:head) %>
  </head>

  <body>
    <%= render 'navbar' %>

    <div class="container my-3">
      <div id="flash_messages">
        <%= render 'flash' %>
      </div>

      <div id="page_content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div id="orders_list">
  <div class="container">
    <h1>Orders</h1>

    <table class="table">
      <thead>
      <tr>
        <th>Order ID</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Status</th>
        <th>Stripe Payment Intent ID</th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
      <% product = order.product %>

        <tr>
          <td><%= order.id %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= order.status %></td>
          <td><%= order.stripe_payment_intent_id %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/new_complete.html.erb
<div class="mb-2">
  <table class="table">
    <tr>
      <td>
        <h5>
          <%= @product.name %> - <%= number_to_currency(@product.price, precision: 2) %>
        </h5>
      </td>
    </tr>
  </table>
</div>

<div id="payment-element"></div>
<%= button_tag 'Pay', class: 'btn btn-primary mt-2', id: 'pay-btn', disabled: true %>


<script>
    document.addEventListener('turbo:load', function() {
        let stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
        let elements = stripe.elements({clientSecret: '<%= @payment_intent.client_secret %>'});
        let paymentElement = elements.create('payment');

        var paymentElementDiv = document.getElementById('payment-element');
        if (paymentElementDiv === null) {
            return;
        }

        paymentElement.mount('#payment-element');

        let payBtn = document.getElementById('pay-btn');

        paymentElement.on('change', function(event) {
            if (event.complete) {
                payBtn.removeAttribute('disabled');
            }
        });

        payBtn.addEventListener('click', function () {
            if(!this.disabled) {
                stripe.confirmPayment({
                    elements,
                    confirmParams: {
                        return_url: '<%= complete_orders_url(id: @order.id) %>',
                    }
                })
                    .then(function(result) {
                        if (result.error) {
                            let flash_messages = document.getElementById('flash_messages');
                            flash_messages.innerText = result.error;
                        }
                    });
            }
        })
    });
</script>

app/views/payment_form/index.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
<% end %>

<div id="payment-element"></div>
<%= button_tag 'Pay', class: 'btn btn-primary' %>

<script>
    window.addEventListener('load', function () {
        const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
        const elements = stripe.elements({clientSecret: '<%= @payment_intent.client_secret %>'});
        const paymentElement = elements.create('payment');

        paymentElement.mount('#payment-element');
    });
</script>

app/views/products/_form.html.erb
<div>
  <%= form_with model: @product do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>

    <div class="form-group my-2">
      <%= f.label :price %>
      <%= f.number_field :price, required: true, step: 0.01, class: 'form-control' %>
    </div>

    <div class="my-2">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/products/_index.html.erb
<div class="container">
  <h1>Products</h1>
  <%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td>
            <%= link_to 'Purchase', new_complete_orders_path(product_id: product.id), class: 'btn btn-primary' %>
            <%= button_to 'Delete', product_path(product.id), method: :delete, class: 'btn btn-primary mt-1' %>
          </td>
        </tr>
     <% end %>
    </tbody>
  </table>
</div>

app/views/products/index.html.erb
<div id="product_list">
  <%= render 'index' %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<div id="product_form">
  <%= render 'form' %>
</div>